### ISSUE TITLE
common commands not found

### ISSUE THREAD

**Issue by m7mdcc** [martinwguy/openwrt#1]
Hi 
Thanks for your work , 

i flashed my mr3220 , but when connect to ssh its say  :\[\e]0;\u@\h: \w\a\]\u@\h:\w\$ either than like root@lede:$

if i run dir  vi no of this command is found , it say  : -ash: vi: not found

Also i can't login to router using winscp via scp protocol .  :(((

is that normal ? 

Thanks again

**Comment by martinwguy** [comment]
Hi! I'm happy you're finding this useful.

Yes, vi is not included by default, as part of the drastic space-saving measures. However, one of the last space-saving measures I found was to compress the Lua files, which saved 256KB of space, so you can include a few more useful things with no problems.

To enable vi, edit MR3220.sh at line 212
    echo        BUSYBOX_CONFIG_VI=n
and change that to =y

Alternatively, once you've downloaded and unpacked everything, you can cd into lede-17.01 and say "make menuconfig" to browse all the possible options, then
    make
and do the last few lines of MR3220.sh to copy the new firmware over and flash it.

"scp" is enabled and MR3220.sh uses it to copy the new firmware to the device in /tmp/fw.bin

I haven't tried it from Windows, as I use Linux-based systems (Debian, the big, boring one) however it "should" work for you.

**Comment by m7mdcc** [comment]
Thanks for your tips , 

You are life saver !

**Comment by martinwguy** [comment]
Thanks for that. My issue was that openwrt's openvpn wouldn't accept the .ovp file that my VPN company gives me, so I'll try that also... when I get round to unbricking the MR!

Blessings
